/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import model.excel;
import model.persona;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFRichTextString;
import org.apache.poi.ss.usermodel.Row;
import project_swing.clsExportarExcel;


/**
 *
 * @author cml_9
 */
public class Home extends javax.swing.JFrame {

    private DefaultTableModel model;
    private JFileChooser FileChooser = new JFileChooser();
    private Vector columnass = new Vector();
    private Vector filass = new Vector();
    private static int tabla_ancho = 0;
    private static int tabla_alto = 0;
    String name;
    ExcelTable extable;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();

        model = new DefaultTableModel();
        datos.setModel(model);
        this.datos.setAutoCreateRowSorter(true);
        datos.setEnabled(false);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        importarPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        importarLabel = new javax.swing.JLabel();
        exportarPanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        exportarLabel = new javax.swing.JLabel();
        CRUDpanel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        CRUDlabel = new javax.swing.JLabel();
        acercaDe = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        advertencia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 35, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        importarPanel.setBackground(new java.awt.Color(41, 57, 80));
        importarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                importarPanelMousePressed(evt);
            }
        });

        jPanel9.setPreferredSize(new java.awt.Dimension(3, 50));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        importarLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        importarLabel.setForeground(new java.awt.Color(255, 255, 255));
        importarLabel.setText("Importar");
        importarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                importarLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout importarPanelLayout = new javax.swing.GroupLayout(importarPanel);
        importarPanel.setLayout(importarPanelLayout);
        importarPanelLayout.setHorizontalGroup(
            importarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importarPanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(importarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        importarPanelLayout.setVerticalGroup(
            importarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(importarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(importarLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(importarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 130, 50));

        exportarPanel.setBackground(new java.awt.Color(23, 35, 51));
        exportarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exportarPanelMousePressed(evt);
            }
        });

        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(3, 50));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        exportarLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exportarLabel.setForeground(new java.awt.Color(255, 255, 255));
        exportarLabel.setText("Exportar");
        exportarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exportarLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exportarPanelLayout = new javax.swing.GroupLayout(exportarPanel);
        exportarPanel.setLayout(exportarPanelLayout);
        exportarPanelLayout.setHorizontalGroup(
            exportarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportarPanelLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(exportarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        exportarPanelLayout.setVerticalGroup(
            exportarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(exportarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exportarLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(exportarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 130, -1));

        CRUDpanel.setBackground(new java.awt.Color(23, 35, 51));
        CRUDpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CRUDpanelMousePressed(evt);
            }
        });

        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(3, 50));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        CRUDlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CRUDlabel.setForeground(new java.awt.Color(255, 255, 255));
        CRUDlabel.setText("CRUD");
        CRUDlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CRUDlabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout CRUDpanelLayout = new javax.swing.GroupLayout(CRUDpanel);
        CRUDpanel.setLayout(CRUDpanelLayout);
        CRUDpanelLayout.setHorizontalGroup(
            CRUDpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRUDpanelLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(CRUDlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );
        CRUDpanelLayout.setVerticalGroup(
            CRUDpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CRUDpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CRUDlabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(CRUDpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        acercaDe.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        acercaDe.setForeground(new java.awt.Color(255, 255, 255));
        acercaDe.setText("?");
        acercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaDeMouseClicked(evt);
            }
        });
        jPanel1.add(acercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jButton1.setText("Agrandar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 570));

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        advertencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        advertencia.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(advertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 11, 305, 48));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Maneja tu datos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel10.setText("X");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 35, 43));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 810, 70));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datosMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(datos);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 810, 500));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 810, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importarPanelMousePressed
        // TODO add your handling code here:
        
        
        
        jPanel9.setOpaque(true);
        jPanel11.setOpaque(false);
        jPanel13.setOpaque(false);
       
        setColor(importarPanel);
        resetColor(exportarPanel);
        resetColor(CRUDpanel);
   
        this.datos.setEnabled(false);
        this.advertencia.setText("");
        
        model = new DefaultTableModel();
        datos.setModel(model);
        datos.setEnabled(true);
        importar();
        
    }//GEN-LAST:event_importarPanelMousePressed

    private void exportarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportarPanelMousePressed
        // TODO add your handling code here:
        jPanel11.setOpaque(true);
        jPanel9.setOpaque(false);
        jPanel13.setOpaque(false);
       
        setColor(exportarPanel);
        resetColor(importarPanel);
        resetColor(CRUDpanel);
    
        this.datos.setEnabled(true);
        
        boolean bueno = true;
        int notaAValidar = 0;
        int notamala = 0;
       
        if(datos.getRowCount()!=0 && bueno){
            this.advertencia.setText("");
            try {
                //-------------------
                clsExportarExcel excelExporter = new clsExportarExcel();
                excelExporter.exportarExcel(datos);
                /*if () {
                    JOptionPane.showMessageDialog(null, "TABLAS EXPORTADOS CON EXITOS!");
                }*/
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }    
        else{
            System.out.println("No hay datos para exportar");
            this.advertencia.setText("Verifique los datos a exportar");
        }
    }//GEN-LAST:event_exportarPanelMousePressed

    private void CRUDpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CRUDpanelMousePressed
        // TODO add your handling code here:
        jPanel13.setOpaque(true);
        jPanel9.setOpaque(false);
        jPanel11.setOpaque(false);
        
        setColor(CRUDpanel);
        resetColor(exportarPanel);
        resetColor(importarPanel);
    }//GEN-LAST:event_CRUDpanelMousePressed

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
        
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged


    
    private void datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datosMouseClicked
        // TODO add your handling code here:
    JTable table = (JTable)evt.getSource();
    int row = table.getSelectedRow();
    int column = table.getSelectedColumn();
    if (column == 0){
        final String valueInCell = (String)table.getValueAt(row, column);
        final String nota1 = (String)table.getValueAt(row,1);
        final String nota2 = (String)table.getValueAt(row,2);
        final String nota3 = (String)table.getValueAt(row,3);
        int promedio = (Integer.parseInt(nota1)+Integer.parseInt(nota2)+Integer.parseInt(nota3))/3;
        String promedio1 = Integer.toString(promedio);
    }
    
    }//GEN-LAST:event_datosMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void exportarLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportarLabelMousePressed
        // TODO add your handling code here:
        
        jPanel11.setOpaque(true);
        jPanel9.setOpaque(false);
        jPanel13.setOpaque(false);
       
        setColor(exportarPanel);
        resetColor(importarPanel);
        resetColor(CRUDpanel);
    
        this.datos.setEnabled(true);
        
        boolean bueno = true;
        int notaAValidar = 0;
        int notamala = 0;

        
        if(datos.getRowCount()!=0 && bueno){
            this.advertencia.setText("");
            try {
                //-------------------
                clsExportarExcel excelExporter = new clsExportarExcel();
                excelExporter.exportarExcel(datos);
                /*if () {
                    JOptionPane.showMessageDialog(null, "TABLAS EXPORTADOS CON EXITOS!");
                }*/
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }    
        else{
            System.out.println("No hay datos para exportar");
            this.advertencia.setText("Verifique los datos a exportar");
        }
        
    }//GEN-LAST:event_exportarLabelMousePressed

    private void importarLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importarLabelMousePressed
        // TODO add your handling code here:
        
        jPanel9.setOpaque(true);
        jPanel11.setOpaque(false);
        jPanel13.setOpaque(false);
       
        setColor(importarPanel);
        resetColor(exportarPanel);
        resetColor(CRUDpanel);
   
        this.datos.setEnabled(false);
        this.advertencia.setText("");
        
        model = new DefaultTableModel();
        datos.setModel(model);
        datos.setEnabled(true);
        importar();
    }//GEN-LAST:event_importarLabelMousePressed

    private void CRUDlabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CRUDlabelMousePressed
        // TODO add your handling code here:
        Inicio crud = new Inicio();
        crud.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CRUDlabelMousePressed

    private void datosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datosMouseEntered
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_datosMouseEntered

    private void acercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaDeMouseClicked
        // TODO add your handling code here:
        
        acercaDe pregunta = new acercaDe(this,true);
        
        pregunta.setVisible(true);
        
        
    }//GEN-LAST:event_acercaDeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        extable.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void importar(){
        JFileChooser examinar = new JFileChooser();
        examinar.setFileFilter(new FileNameExtensionFilter("Archivos excel","xls","xlsx"));
        int opcion = examinar.showOpenDialog(this);
        File archivoExcel = null;
        excel funcionExcel = new excel();
        persona per;
          if(opcion==JFileChooser.APPROVE_OPTION){
                System.out.println("Se ah encontrado Fichero");
                archivoExcel = examinar.getSelectedFile().getAbsoluteFile();
                this.name = examinar.getName(archivoExcel);
                name = name.substring(0,name.length()-4);
                try{
                    
                    funcionExcel.imprimir(funcionExcel.importarArchivo(archivoExcel));
                    System.out.println("Se ah encontrado Fichero");
                    Workbook leerExcel = Workbook.getWorkbook(archivoExcel);
                    System.out.println("Se ah encontrado Fichero");
                    for(int hoja=0;hoja<leerExcel.getNumberOfSheets();hoja++){
                        Sheet hojaP = leerExcel.getSheet(hoja);
                        int columnas = hojaP.getColumns();
                        int filas = hojaP.getRows();
                        Object data[] = new Object[columnas];
                        for(int fila=0;fila<filas;fila++){
                            for(int columna = 0;columna<columnas;columna++){
                                if(fila==0){
                                    model.addColumn(hojaP.getCell(columna, fila).getContents());
                                    
                                    //model.addColumn();
                                }
                                //System.out.println(hojaP.getCell(columna,fila).getContents());
                                if(fila>=1){
                                    data[columna] = hojaP.getCell(columna,fila).getContents();
                                }                    
                            }
                            model.addRow(data);
                        }
                    }
                   model.removeRow(0);
                }
                catch(IOException | BiffException ex){
                    System.out.println("No se pudo importar el archivo excel");

                }   
            }
            else{
                System.out.println("El fichero no existe");
            }
          
          extable = new ExcelTable(this,true,model);
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    private void setColor(JPanel panel){
        panel.setBackground(new Color(41,57,80));
    }
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(23,35,51));
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CRUDlabel;
    private javax.swing.JPanel CRUDpanel;
    private javax.swing.JLabel acercaDe;
    private javax.swing.JLabel advertencia;
    private javax.swing.JTable datos;
    private javax.swing.JLabel exportarLabel;
    private javax.swing.JPanel exportarPanel;
    private javax.swing.JLabel importarLabel;
    private javax.swing.JPanel importarPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
